<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Italcom.AgentOrchestrator.Application\Italcom.AgentOrchestrator.Application.csproj" />
    <ProjectReference Include="..\Italcom.AgentOrchestrator.Domain\Italcom.AgentOrchestrator.Domain.csproj" />
  </ItemGroup>

</Project>
