<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="11.0.0-preview.1.26104.118" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-preview.1.26104.118" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="11.0.0-preview.1.26104.118" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Italcom.AgentOrchestrator.Application\Italcom.AgentOrchestrator.Application.csproj" />
    <ProjectReference Include="..\Italcom.AgentOrchestrator.Domain\Italcom.AgentOrchestrator.Domain.csproj" />
  </ItemGroup>

</Project>
