<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Italcom.AgentOrchestrator.Application\Italcom.AgentOrchestrator.Application.csproj" />
    <ProjectReference Include="..\Italcom.AgentOrchestrator.Infrastructure\Italcom.AgentOrchestrator.Infrastructure.csproj" />
  </ItemGroup>

</Project>
