<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Italcom.AgentOrchestrator.Domain\Italcom.AgentOrchestrator.Domain.csproj" />
    <ProjectReference Include="..\..\src\Italcom.AgentOrchestrator.Application\Italcom.AgentOrchestrator.Application.csproj" />
    <ProjectReference Include="..\..\src\Italcom.AgentOrchestrator.Infrastructure\Italcom.AgentOrchestrator.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Italcom.AgentOrchestrator.AgentRuntime\Italcom.AgentOrchestrator.AgentRuntime.csproj" />
    <ProjectReference Include="..\..\src\Italcom.AgentOrchestrator.Api\Italcom.AgentOrchestrator.Api.csproj" />
    <ProjectReference Include="..\..\src\Italcom.AgentOrchestrator.Cli\Italcom.AgentOrchestrator.Cli.csproj" />
  </ItemGroup>

</Project>